variable "rg_obuoc_name" { }
variable "rg_obuoc_location" { }
variable "tags" { }
variable "suffix" { }
variable "environment" { }
variable "core_storageaccount_name" { }
variable "core_sa_container_names" { }
variable "tsdbtm_storageaccount_name" { }
variable "cdn_storageaccount_name" { }
variable "linux_app_service_subnet_id" { }
variable "windows_app_service_subnet_id" { }
variable "obtsync_app_service_subnet_id" { }
variable "azureservices_subnet_id" { }
variable "appgatway_subnet_id" { }
variable "core_sa_event_archive_container_name" { }
