variable "azure_eventhub_namespace" { }
variable "eventhub_sku" { }
variable "suffix" { }
variable "environment" { }
variable "eventhub_capacity" { }
variable "rg_obuoc_name" { }
variable "rg_obuoc_location" { }
variable "eventhub_obtevents_name" { }
variable "eventhub_telemetry_name" { }
variable "linux_app_service_subnet_id" { }
variable "windows_app_service_subnet_id" { }
variable "obtsync_app_service_subnet_id" { }
variable "azureservices_subnet_id" { }
variable "appgatway_subnet_id" { }
variable "consumer_group_names_obtevents" { }
variable "consumer_group_names_telemetry" { }
variable "eventhub_partition_count" { }
variable "eventhub_message_retention" { }
variable "tags" { }