variable "terrclient_id" { }
variable "terrclient_secret" { }
variable "client_id" { }
variable "app_name" { }
variable "client_secret" { }
variable "subscription_id" { }
variable "tenant_id" { }
variable "suffix" { }
variable "storagesuffix" { }
variable "environment" { }
variable "rg_obuoc_name" { }
variable "rg_obuoc_location" { }
variable "tags" { }
variable "obuoc_vnet_name" { }
variable "obuoc_vnet_address" { }
variable "azureservices_subnet_name" { }
variable "azureservices_subnet_address" { }
variable "linux_app_service_subnet_name" { }
variable "linux_app_service_subnet_address" { }
variable "windows_app_service_subnet_name" { }
variable "windows_app_service_subnet_address" { }
variable "obtsync_app_service_subnet_name" { }
variable "obtsync_app_service_subnet_address" { }
variable "agw_subnet_name" { }
variable "appgw_subnet_address" { }
variable "azure_keyvault_name" { }
variable "azure_eventhub_namespace" { }
variable "eventhub_sku" { }
variable "eventhub_capacity" { }
variable "eventhub_obtevents_name" { }
variable "eventhub_telemetry_name" { }
variable "consumer_group_names_obtevents" { }
variable "consumer_group_names_telemetry" { }
variable "eventhub_partition_count" { }
variable "eventhub_message_retention" { }
variable "core_storageaccount_name" { }
variable "core_sa_container_names" { }
variable "tsdbtm_storageaccount_name" { }
variable "cdn_storageaccount_name" { }
variable "azure_entity_postgresql_name" { }
variable "postgresql_sku_name" { }
variable "postgresql_storage_mb" { }
variable "postgresql_backup_retention_days" { }
variable "postgresql_geo_redundant_backup" { }
variable "postgresql_server_version" { }
variable "postgresql_ssl_enforcement" { }
variable "postgresql_db_names" { }
variable "postgresql_db_charset" { }
variable "postgresql_db_collation" { }
variable "azure_events_postgresql_name" { }
variable "postgresql_events_db_names" { }
variable "pdb_admin_login_akv_key" { }
variable "pdb_admin_pwd_akv_key" { }
variable "time_series_insights_telemetry_name" { }
variable "event_source_Name" { }
variable "law_name" { }
variable "appinsights_name" { }
variable "user_audit_appinsights_name" { }
variable "linux_app_service_plan_name" { }
variable "windows_app_service_plan_name" { }
variable "obtsync_app_service_plan_name" { }
variable "obtsync_app_service_name" { }
variable "webui_app_service_name" { }
variable "graphql_entity_app_service_name" { }
variable "graphql_event_app_service_name" { }
variable "timeseries_api_app_service_name" { }
variable "utility_app_service_name" { }
variable "windows_function_app_name" { }
variable "azure_signalr_name" { }
variable "agw_public_ip_address_name" { }
variable "public_ip_allocation_method" { }
variable "public_ip_address_sku" { }
variable "agw_name" { }
variable "app_gateway_sku_name" { }
variable "app_gateway_sku_tier" { }
variable "app_gateway_sku_capacity" { }
variable "route_obtsync" { }
variable "route_graphqlevent" { }
variable "route_graphqlentity" { }
variable "route_storage" { }
variable "route_utility" { }
variable "route_timeseriesapi" { }
variable "route_eventhub_telemetry" { }
variable "storage_zone" { }
variable "app_zone" { }
variable "keyvault_zone" { }
variable "postgresql_zone" { }
variable "eventhub_zone" { }
variable "fn_storage_subresource_names" { }
variable "postgresql_subresource_names" { }
variable "key_vault_subresource_names" { }
variable "event_hub_subresource_names" { }
variable "function_subresource_names" { }
variable "signalr_subresource_names" { }
variable "route_eventprocessor" { }
variable "ar_app_password" { }
variable "open_blue_aad_client_secret" { }
variable "vm_size"  {} 
variable "vm_storage_acc_type" { }
variable "vm_adminuser" { }
variable "ercollection_id" { }
variable "ob_client_id" { }
variable "ob_graphql_id" { }
variable "ob_scope" { }
variable "ob_tenant_id" { }
variable "website_dns_server" { }
variable "obt_keycloak_client_id" { }
variable "obt_keycloak_login_host" { }
variable "obt_keycloak_realm" { }
variable "obt_keycloak_username" { }
variable "obt_keycloak_password" { }
variable "forge_auth_url" { }
variable "jwks_uri" { }
variable "msal_tenant_id" { }
variable "msal_client_id" { }
variable "msal_ts_scope" { }
variable "ar_keycloak_url" { }
variable "ar_tenant_url" { }
variable "ar_app_username" { }
variable "ar_client_id" { }
variable "ar_sop_service_url" { }
variable "ar_sop_service_new_url" { }
variable "obt_graphql_url" { }
variable "obt_subscription_id" { }
variable "ob_consumer_group" { }
variable "ob_eventhub" { }
/*variable "backend_resource_group" { }
variable "backend_storage_account" { }
variable "backend_container" { }
variable "backend_subscription_id" { }
variable "backend_tenant_id" { }
variable "backend_client_id" { }
variable "backend_client_secret" { }
variable "environment" { }*/
variable "forge_client_id" { }
variable "forge_client_secret" { }
variable "autodesk_url" { }
variable "gql_tenantid" { }
variable "gql_clientid" { }
variable "gql_secret" { }
variable "gql_scope" { }
variable "gql_url" { }
variable "az_ad_tenantid" { }
variable "endpoint" { }
variable "issuer" { }
variable "valid_audiences" { }
variable "audiences" { }
variable "downloadfolderpath" { }
variable "gqlclienttimeout" { }
variable "ping_utility_ercollectionid" { }
variable "azurerm_kusto_cluster_name" { }
variable "adx_sku_name_size" { }
variable "azurerm_kusto_database_name" { }
variable "adx_subresource_names" { }
variable "eventhub_ns_name" { }
variable "eventhub_name" { }
variable "consumer_group_name" { }
variable "eventhub_connection_name" { }
variable "kusto_zone" { }
variable "adx_app_id" { }
variable "uoc_maptiler_map_conn_str" { }
variable "uoc_maptiler_tile_conn_str" { }
variable "sxs_graphql_url" { }
variable "uoc_memeber_of_api_url" { }
/*variable "dev_cors_url" { }
variable "test_cors_url" { }
variable "stage_cors_url" { }
variable "prod_cors_url" { }*/
variable "app_log_utility_url" { }
variable "windows_function_app_names" { }
variable "ob_consumer_groups" { }
variable "ob_eventhubs" { }
variable "cors_url" { }
variable "core_sa_event_archive_container_name" { }
variable "prod_replica_resource_group"  { }
variable "prod_replica_subscription_id" { }
variable "prod_replica_environment" { }
variable "prod_replica_suffix" { }
variable "BOTNOTCH_ENDPOINT_FOR_EVENTS" { }
variable "BOTNOTCH_ENDPOINT_FOR_TURNSTILE_DETAILS" { }
variable "BOTNOTCH_API_BEARER_TOKEN" { }
variable "obt_event_graphql_url" { }
variable "obt_event_gql_url" { }
variable "uoc_msal_tenant_id" { }
variable "uoc_msal_client_id" { }
variable "uoc_msal_client_secret" { }
variable "uoc_msal_scope" { }