variable "azurerm_kusto_cluster_name" { }
variable "rg_obuoc_location" { }
variable "adx_sku_name_size" { }
variable "tags" { }
variable "rg_obuoc_name" { }
variable "suffix" { }
variable "environment" { }
variable "azurerm_kusto_database_name" { }
variable "eventhub_ns_name" { }
variable "eventhub_name" { }
variable "consumer_group_name" { }
variable "eventhub_connection_name" { }
variable "eventhub_telemetery_id" { }
variable "eventhub_consumergroup_telemetery_2" { }