variable "rg_obuoc_name" { }
variable "tags" { }
variable "storage_zone" { }
variable "vnet_id" { }
variable "app_zone" { }
variable "keyvault_zone" { }
variable "postgresql_zone" { }
variable "eventhub_zone" { }
variable "kusto_zone" { }