variable "rg_obuoc_name" { }
variable "rg_obuoc_location" { }
variable "tags" { }
variable "suffix" { }
variable "environment" { }
variable "time_series_insights_telemetry_name" { }
variable "azure_eventhub_namespace" { }
variable "eventhub_telemetry_name" { }
variable "consumer_group_names_telemetry" { }
variable "event_source_Name" { }
variable "tsdbtm_storageaccount_name" { }
variable "tsdbtm_storage_account_primary_access_key" { }
variable "eventhub_telemetry_id" { }
variable "eventhub_telemetry_policy_listen_primary_key" { }
variable "client_id" { }
variable "app_name" { }
