variable "rg_obuoc_name" { }
variable "rg_obuoc_location" { }
variable "tags" { }
variable "suffix" { }
variable "environment" { }
variable "private_dns_zone_ids" { }
variable "subresource_names" { }
variable "private_connection_resource_id" { }
variable "subnet_id" { }
variable "endpointname" { }