variable "rg_obuoc_name" { }
variable "rg_obuoc_location" { }
variable "tags" { }
variable "suffix" { }
variable "environment" { }
variable "keyvault_id" { }
variable "linux_app_service_plan_name" { }
variable "windows_app_service_plan_name" { }
variable "obtsync_app_service_plan_name" { }
variable "obtsync_app_service_name" { }
variable "windows_app_service_subnet_id" { }
variable "obtsync_app_service_subnet_id" { }
variable "webui_app_service_name" { }
variable "graphql_entity_app_service_name" { }
variable "linux_app_service_subnet_id" { }
variable "graphql_event_app_service_name" { }
variable "timeseries_api_app_service_name" { }
variable "utility_app_service_name" { }
variable "windows_function_app_name" { }
variable "core_storageaccount_name" { }
variable "core_storage_account_primary_access_key" { }
variable "ai_instrumentation_key" { }
variable "ai_connection_string" { }
variable "forge_auth_url" { }
variable "ercollection_id" { }
variable "ob_client_id" { }
variable "ob_graphql_id" { }
variable "ob_scope" { }
variable "ob_secret" { }
variable "ob_tenant_id" { }
variable "pg_connection_string" { }
variable "uoc_core_sa_conn_string" { }
variable "core_sa_container_names" { }
variable "subscription_id" { }
variable "website_dns_server" { }
variable "obt_keycloak_client_id" { }
variable "obt_keycloak_login_host" { }
variable "obt_keycloak_password" { }
variable "obt_keycloak_realm" { }
variable "obt_keycloak_username" { }
variable "audience" { }
variable "entity_db_url" { }
variable "event_db_url" { }
variable "issuer_uri" { }
variable "jwks_uri" { }
variable "az_ts_fqdn" { }
variable "msal_tenant_id" { }
variable "msal_client_id" { }
variable "msal_client_secret" { }
variable "msal_ts_scope" { }
variable "ping_utility_ercollectionid" { }

variable "ar_keycloak_url" { }
variable "forge_client_id" { }
variable "forge_secret" { }
variable "ar_tenant_url" { }
variable "ar_app_username" { }
variable "ar_app_password" { }
variable "ar_client_id" { }
variable "ar_sop_service_url" { }
variable "ar_sop_service_new_url" { }
variable "obt_msal_client_id" { }
variable "obt_graphql_url" { }
variable "obt_subscription_id" { }
variable "evh_obuoc_obtevents_readonly" { }
variable "ob_consumer_group" { }
variable "ob_eventhub" { }
variable "evh_obuoc_telemetry_write" { }
variable "telemetryeventhubname" { }
variable "pgsql_obuoc_entity_evproc_conn_string" { }
variable "pgsql_obuoc_events_evproc_conn_string" { }
variable "client_id" { }
variable "tenant_id" { }
variable "client_secret" { }
variable "appgatway_subnet_id" { }
variable "azureservices_subnet_id" { }
variable "endpoint" { }
variable "issuer" { }
variable "valid_audiences" { }
variable "signalr_connection_string" { }
variable "adx_connection_string" { }
variable "adx_app_id" { }
variable "azurerm_kusto_database_name" { }
variable "uoc_maptiler_map_conn_str" { }
variable "uoc_maptiler_tile_conn_str" { }
variable "sxs_graphql_url" { }
variable "uoc_memeber_of_api_url" { }
/*variable "dev_cors_url" { }
variable "test_cors_url" { }
variable "stage_cors_url" { }
variable "prod_cors_url" { }*/
variable "app_log_utility_url" { }
variable "windows_function_app_names" { }
variable "evh_obuoc_telemetry_readonly" { }
variable "ob_consumer_groups" { }
variable "ob_eventhubs" { }
variable "cors_url" { }
variable "core_sa_event_archive_container_name" { }
variable "BOTNOTCH_ENDPOINT_FOR_EVENTS" { }
variable "BOTNOTCH_ENDPOINT_FOR_TURNSTILE_DETAILS" { }
variable "BOTNOTCH_API_BEARER_TOKEN" { }
variable "obt_event_graphql_url" { }
variable "obt_event_gql_url" { }
variable "uoc_msal_tenant_id" { }
variable "uoc_msal_client_id" { }
variable "uoc_msal_client_secret" { }
variable "uoc_msal_scope" { }