variable "obuoc_vnet_name" { }
variable "rg_obuoc_name" { }
variable "rg_obuoc_location" { }
variable "suffix" { }
variable "environment" { }
variable "obuoc_vnet_address" { }
variable "azureservices_subnet_name" { }
variable "azureservices_subnet_address" { }
variable "linux_app_service_subnet_name" { }
variable "linux_app_service_subnet_address" { }
variable "windows_app_service_subnet_name" { }
variable "windows_app_service_subnet_address" { }
variable "obtsync_app_service_subnet_name" { }
variable "obtsync_app_service_subnet_address" { }
variable "agw_subnet_name" { }
variable "appgw_subnet_address" { }
variable "tags" { }